language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    #https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=3
    #   osx_image: xcode7.3
    #   # OS X 10.11
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=2
    #   osx_image: xcode7.3
    #   # OS X 10.11
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=3
    #   osx_image: xcode7.1
    #   # OS X 10.10
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=2
    #   osx_image: xcode7.1
    #   # OS X 10.10
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    - os: osx
      language: generic
      env: PY_VERSION=3
    - os: osx
      language: generic
      env: PY_VERSION=2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_before_install.sh;  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev libtiff4-dev libx11-6 libX11-dev xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sdl-config --libs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -la /usr/X11R6/include; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_EXE=python PIP_CMD=pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx.sh; fi
  - "$PIP_CMD install --upgrade setuptools pip"
  - "$PIP_CMD install --upgrade numpy"
  - "$PYTHON_EXE config.py -auto"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON_EXE setup.py install -noheaders; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_install.sh; fi
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
    - secure: FFDtLNuNWlSwgsPeElNzXq3vUc5tgrEdMZyJVmTGigxhsjd7zkd2QID7dFn6P8ma8Du70qTjKGoTz2GnZeJ8hrYjk206jMrAmzKHDme/fCyz65NGGrxpKE3sMhE/LPYQbOMWtQBeG67edEA9Xy8rop1SVBnViTieConNGJGnB5jPcZRnJXERBcvUV8Tnl9PBREJTNUdKJm71irpWmlXk41NDXuPk4ZkS9MM6im3LnuzaRKHAaoklyZtiHphmfYhkD8i60JpXNNOoBFHF0vjf4hCkYCc2Pf9jO0pIGQAGbhwLnNI3RzPZiESb5rc8KqIUZ2vWdxG5KdLH9oyziMn0qlkSSe1uYnrL0K1coKK+x0yCm8C7p9EEUItdRQJICalXPnDKBPrU4qhcb77dHgu8OOOEiJiyPzu5rCrVY3/KRcgssWilft28lI6R2THRDy3ySU2aDHXJDQf3w+Nw76pAc3AO3jIIPHYD5v56PjpxEVmY1/oDJ6vZn3ebwxj/b+qN+Oq3n61x+JNB4we2xRtIFgy9m8yeKauPm0AL6VWh8q0+8G5mvxc2TKxxtbqRWw/sPlHDd5sJuejIQ/0izYgIxw8Dt346qyjgjTbPhiY9ERatP76QepBxzzROTATacInx9xqSvsa4PAdUG9jnyVs87TXXBwLgWURrBoBXWLpCSb4=
    - secure: kxL0WYTl8O72KEeKfXzMDVjUq7BEfaatK3t6Y+fK+5jf5OvNFwH5FiJucp+u4BwNtIdqua7sRnPJL0Jw1tDNyofNyqIIEwO6rccFCTtQ798x/U54zzE9X4NDNUcOBGtFCjOQlppu/AetWRouBZQjpDzOHtgwv2JydnVUsefa/XSHvw1VGgYS4o2VU0qhiAS7BYgWmY3brChxJXgP96dAnLIC5hvD9MixRiX2xtUSjulVZWZVdfFIEPWIX1kT2ZFCnrU+zLZJn4QQn6iL+9ZiBrJfPzKjFADfZkT9wXrMPc9VKhMaxxu0QSnGWUCzK2HGj7OkH8BIBypBQic2mcKoLz0mZPpeI9XUckMVzuBizqFuPlCmldITdZrtsYj3uS3dNjh+vXg24ZiWlBFtsUvVBKBkVOivpxTOqx4SYI+Gy8cxRGrwtV7QFmBgo3cnz0HvEW7e5cSpVJhR4BKqASO+MUuLiab7HUP9872KQL9vIUDtR0m4O5mQrwl79MKsnTx+ODPFKNseOiFewEsnOyAOJ8dgZbVPqp1PQ1ZucyC3q0Sca615CsU74HG+N+6C11RclmuFKa0YNNWbelIEFLYUMtt/X2zC8xYstcM9kAIe9Mq5t1HuB9rEbf4hsdrK2ij3eoyYgyDD3gR+GLl8DR6LNhftRDjej7FnanYxyQQK3Rw=
script:
  - "$PYTHON_EXE -m pygame.tests.__main__ --exclude opengl"
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_after_success.sh; fi
