language: python
matrix:
  include:
    # - os: linux
    #   sudo: required
    #   python: 2.7
    # - os: linux
    #   sudo: required
    #   python: 3.4
    # - os: linux
    #   sudo: required
    #   python: 3.5

    #https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=3
    #   osx_image: xcode7.3
    #   # OS X 10.11
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=2
    #   osx_image: xcode7.3
    #   # OS X 10.11
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=3
    #   osx_image: xcode7.1
    #   # OS X 10.10
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip
    # - os: osx
    #   language: generic
    #   env: PY_VERSION=2
    #   osx_image: xcode7.1
    #   # OS X 10.10
    #   cache:
    #     directories:
    #       - $HOME/.cache/pip

    # - os: osx
    #   language: generic
    #   env: PY_VERSION=3
    - os: osx
      language: generic
      env:
        - PY_VERSION=2
        - MAKEFLAGS=-j8
        # - MACOSX_DEPLOYMENT_TARGET=10.6
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/Library/Caches/Homebrew
before_install:
  - set | grep PYPI_ > .travis_tmp
  - $(set | grep PYPI_ | python -c "import sys;print('\n'.join(['unset %s' % l.split('=')[0] for l in sys.stdin.readlines() if l.startswith('PYPI')]))")
  - travis_wait 40 if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_before_install.sh;  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev libtiff4-dev libx11-6 libX11-dev xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sdl-config --libs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -la /usr/X11R6/include; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_EXE=python PIP_CMD=pip; fi
  - "$PIP_CMD install --upgrade setuptools pip"
  - "$PIP_CMD install --upgrade numpy"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $PIP_CMD install delocate twine; fi
  - "$PYTHON_EXE config.py -auto"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON_EXE setup.py install -noheaders; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_install.sh; fi
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
script:
  - "$PYTHON_EXE -m pygame.tests.__main__ --exclude opengl -m 8"
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_after_success.sh; fi
after_script:
  - rm -f .travis_tmp
