language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PY_VERSION=2
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sdl-config --libs; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -la /usr/X11R6/include; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_EXE=python PIP_CMD=pip; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx.sh; fi
- "$PIP_CMD install --upgrade setuptools pip"
- "$PIP_CMD install --upgrade numpy"
- "$PYTHON_EXE config.py -auto"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON_EXE setup.py install -noheaders;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_install.sh; fi
env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=disk
  - secure: LJWYBg6bfh8g/Ku3Dzu3GEfEn9VbTpx6TT9f/D4Ld1z3CXgABGFpj155DtsO+Rs9vPDklh6BMcyf6Dx4fuiX8ZAtr6fTR82iM13KIiNQDqjd3taX3ctgKkpQ6l0X2GC1z/zDVm6UBBFz0u6entpkOoD/1n+dHuMTXTIfmCg6JdSnbSPXgUaHyINPW9tw5Ds7q884nA1cYJF201UIy3Kr1JSxTXuxgQyokwDMhadZecxUzJAy1a59rxybEJIBlFp6GnilF7nXzr62Q/Y+KYl+b6UuTj/SdfazuSIi6FWW2a6Ffj2ZI9JM/oO3Rb5VXy8iw9wWDocjY2ZWSf5J6R4JuJEhAFhf+n1bkRamF00ix6s42dLE52/O3khEsb8V7KLb2Z0qTsY7ApcxHR6BSq9dxsVPqcsvkkgAIKALVAJ8JOgeZAWAi6Eb4d7uxAIcBRf1hewgq5zJUzDPkMdo9+BD0YOmIeN2iWqW/JPfR9GOWzeQvTZncFPLGZMuuUNs+Dnu0LtBqxKjGy7eLHbIxOGRXsdqrzxUoukPIwvlMjGvrm02lNj9lDc7vwRD0zniQBGgK/bUw2NKGf20ZCeaNYN+vHSazKHBkOrUeoxR2VurRMgdMnjyT87DYdnIo2dqBgr5dH232V4CbKhM9jv/itzLVcotvFnaIf9LaV3HM0kd214=
  - secure: QcQ7KVLEvYr6hkVeQfbLmMOQhyAUO5X0aPi516EFZ39zkkR94X4vUyXICTQKcxf9ZpJSD2tO0HvjhvgNJqXO59dZVN2fWAbs6N9qSQIVJfgcGwTkRwVszmf6H2ORDmNXHIVfn4JPmJ3EhSYXGNT52zxdFKhvBd9bsdJUg3yUpimOmIpDdg647M1+ZNRQMiAIdvDbzM1SpTjp4RH3vN6vlxnHbnoLUzgOpNDneVwygLYqqg7QliMNjprFVQBPYtHeoo7cecym+x064eKYZBCqM0GB5vdQa2+Sr2lXonxWTGn5J/d17e2ogk5B26XS3sqT4xPQnMKwC8IOPnGC+YjNUBBSN6ujwNVCus8VefqR8m7wW7snfwIMhBd4FpsCWhup9tUUsIQ5zA7ovlrkDx1by4QbVa2vy28cbzE7plTGW3WMhs7h0Mfl5+zEG7DLucoUPbapH70wGNmcrCFDdfZRulTeepHnCmlOP+hFB4TmRdL8yPQbG4xMT9MeBe15+QTOt5pAjjlskA+DXn6na7lCQ07vDYzPo6XbcA70xqkar04I7DPn9z1Wtse6YlS73jegAT74xuV/qw8Cg2jMELSne1vSHfuZr9lPK2+bNs1CT+t9nqroGeo0CaJ2y72UIB1/OOkzV4HzMfsrbk53HnAj+Ra60PFKesHgJRKigb+3LX0=
  - secure: wX/NQP3yPFD41yY2iZPrSLVVXpo+4lVIhXPx2SmjwOupsg5RlWls+AU7q7GoUG2TBANgiqAtPI0nlAeGq13y3v+1zs8Jq7fNj1FMluCRdcNveTAi8Q9bOoiAPFjS4oExML1+XTZrPjdIYgSCc5Al75Lq3r05Fp/X1FGzvRawMNQ8D1/0BvwvtzqzzUh5KUlsx8F3623qbZG3pjC/5tgIERk58eA7j9W4AG7NS96Jywp7Nflt/Hfw/cOo1VbXSu++T+4Ua80/2dFPTxv9osV657xNnYxl75jWTa8qBRghkRO0n2Rv41VG3Q+LYmHjfI3hKrirZUaOjj3iI5Rrdi75+Ayopu16aRKxhp2fwYE4Z4OEEf9VZInZhXHiTw3j0S8kKn/lxiA49NmtnhlL7bMzmFUsSWUb8buXW5uuGwVpRfv/0xQxllJBnKYwJ3j0JO3L14BtK7TQZK+czkeEfIMzHBWHdO3a7HTazJ9YrD1fcGZE89bgUkSj2alvDyLEEmiRsUSDe9bNByZG+JNnmX75nhnHaBMKygm7TYN94SQ/mQSMgGWGGB2177xqBv6V9jr+g9JdztvCisLNk3PYxG4aP2nLGgTL06z6rSjUND5MInzC6DoVYXldCjwg3Caa/P+LfSsABrk1Q4YyjhxPubpwbANTSMoZmVIy5SEYUKQRlx8=
script:
- "$PYTHON_EXE -m pygame.tests.__main__ --exclude opengl"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_before_install.sh; fi
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_after_success.sh; fi
