language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PY_VERSION=2
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_before_install.sh;
  fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sdl-config --libs; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -la /usr/X11R6/include; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_EXE=python PIP_CMD=pip; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx.sh; fi
- "$PIP_CMD install --upgrade setuptools pip"
- "$PIP_CMD install --upgrade numpy"
- "$PYTHON_EXE config.py -auto"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON_EXE setup.py install -noheaders;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_install.sh; fi
env:
  global:
  - secure: uaRdZNhheDbD5Axa2+xCMcriA4TzDlbO+BJvF1skdxOVVjZEWRavPfRQeZnfgKV31Gfs6jPnttzDNsjGx+NtXyxvMhEzOrzYPScV7wErVuWoM7cctlbSjQ2W5ZZ6oNVscAvzm8dK646Cejt7QoiX34hilA76qEerJvuw2izviB2g8LR5cu3l9bMrz3Gtpa78Rtmr3v4HYu8xLem+RyfKuqKyEvm7heAJ2fpiZsZ3/oFc2iUSCfqpLbEMXW/9lzA73RYEudYdEC8ZP8voFwaptq9nTYH2wAcE/B7q4ilsCY8js/advxtJhkyhFCx4zczovpk75yeaznWSLBa6uXiZGY87xMj/J7U1kS2xW31kRkP/WF20gIJDd6ugGCcRksDDe1IkEsUiVCcmVjSrzSt13RTvBk0TkhwEbT/0BUJ9fhgrXKIO1siA9vMoxqTIHvELmPoT4BSHzQQ4gBqGDjOv92jOvvy1RBDqnNUYxP06OXfCQiMV1A5+A05d1Rld/MCtq3ECLrBojNkcGk6Gej/A0tbVHT4d5n6ZeTFAFqCcsEQX2pH2S0FRpJRFT+/jfDSdzhNkRGtg/8MvC5QwAnrRquNSlm26+nMhYFBnavE9eokgfQe9skFk3RLES4RIDHV+PCQyD5cIoj0cHQUV51v28Nd4JzK5Mdu7/KNMVVC7pm0=
  - secure: FXWd4lrmyQi6BtP8Mq8vlPMsjzrQPGJROEWWeabE29E6/9Od6utR+tNKCflmgIjbc94m1oiph9vI44c+P3eVpKfjj9+FXfTqXGi6sSmeTmCV+H9P1Xuy2pkHoz8M41cx/a8cG8YtkG3Xk8vHXCb1cRN2CQvMrQkllTMLvP3+LG7GImusQ0CS8/X9x0RGqYHMKgvcTwf9ruTqYW32skGmBk1J1TUZ5GliyrLvhovn1ojOvPFRslJlikzG88K9+VmrfkwHdibUflpbTHmfJCCJkaNtJDepKazLiuGACRPXeI7l4ApyqdumNh/6teAlv3wRaS9M99ojAHX0jM5x4RfDUk7iyjNzGxn7QkHukRdU/GykcCxEnbkNf03xcj+hmy0n/unyQZFj58VG0BiafRnlN9qgrEURVWLMh7fVxusPnH5ULvC/p3bUojOdnYefWe+kDhdP0uTpujSCio02/amam12Rgr7Yonkhjm99RxYw+siqBsJPZZW8WPIDrq5yz26UXgbSSfxXbOBqJMLFZTp+E2c9UJMyN729EKMlEODqbr3E0Ui0K8eqnKX4TN/f35ZRYb0qlUrWJoX8/3k7KmpfREtP0ieGyzsIqNWTlakW9aoUWponTvNvd/NQtxcdaLSsHY5Rybwl15MiuDVD4xm7w2twu1fYuahTZE9/xgtBiKs=
script:
- "$PYTHON_EXE -m pygame.tests.__main__ --exclude opengl"
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_osx_after_success.sh; fi
